name: Deploy Dev - Vercel

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via Vercel Hook
        env:
          VERCEL_HOOK_DEV: ${{ secrets.VERCEL_HOOK_DEV }}
        run: |
          curl -X POST $VERCEL_HOOK_DEV
